import type { Experience } from '../types/experience';
import { RICH_OVERLAYS } from './experience-seed-rich-overlays';

const IMG = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;

const now = '2026-06-01T00:00:00.000Z';

function exp(partial: Experience): Experience {
  const overlay = RICH_OVERLAYS[partial.id] ?? {};
  return { ...partial, ...overlay };
}

export const experienceSeedData: Experience[] = [
  exp({
    id: 'exp-001',
    slug: 'heritage-old-bengaluru-walk',
    source: 'gamana_native',
    title: 'Old Bengaluru Heritage Walk',
    shortDescription: 'Colonial lanes, markets, and hidden courtyards with Gamana audio context.',
    longDescription:
      'Walk through Basavanagudi and Chickpet with curated stops tied to Gamana stories. Pair with in-app narration before or after your guided segments.',
    gamanaEditorialSummary:
      'Our editorial pick for first-time visitors who want history with neighbourhood texture—not a generic hop-on bus.',
    heroImageUrl: IMG(5765818),
    photoUrls: [IMG(5765818), IMG(3522880)],
    category: 'Heritage',
    experienceType: 'Guided Tour',
    tags: ['heritage', 'walking', 'markets'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Basavanagudi',
    latitude: 12.9432,
    longitude: 77.5675,
    durationMinutes: 180,
    languages: ['English', 'Hindi', 'Kannada'],
    difficultyLevel: 'easy',
    familyFriendly: true,
    priceFrom: 1899,
    priceCurrency: 'INR',
    ratingValue: 4.8,
    ratingSource: 'internal',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Bull Temple entrance, Basavanagudi',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Licensed guide', 'Bottled water', 'Gamana story links'],
    exclusions: ['Meals', 'Hotel pickup'],
    knowBeforeYouGo: 'Wear comfortable shoes; modest dress for temple stops.',
    cancellationPolicy: 'Free cancellation up to 24 hours before start.',
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000102',
    linkedStoryLabel: 'Bull Temple story',
    qualityScore: 92,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'city tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-002',
    slug: 'tipu-palace-guided-heritage',
    source: 'bokun',
    sourceVendorId: 'vendor-karnataka-heritage',
    sourceProductId: 'bokun-tipu-101',
    title: "Tipu's Summer Palace & Fort Trail",
    shortDescription: 'Indo-Islamic architecture and Mysorean resistance history with expert commentary.',
    gamanaEditorialSummary:
      'Pairs naturally with our Tipu Sultan story—book after listening for deeper context on site.',
    heroImageUrl: IMG(3522880),
    photoUrls: [IMG(3522880)],
    category: 'Heritage',
    experienceType: 'Guided Tour',
    tags: ['palace', 'history'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Kalasipalya',
    latitude: 12.9593,
    longitude: 77.5737,
    durationMinutes: 150,
    languages: ['English'],
    difficultyLevel: 'easy',
    minAge: 6,
    familyFriendly: true,
    priceFrom: 2400,
    priceCurrency: 'INR',
    ratingValue: 4.6,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'meet_or_pickup',
    meetingPointText: 'Tipu Sultan Summer Palace ticket counter',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['Entry tickets', 'Guide'],
    exclusions: ['Food'],
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000104',
    linkedStoryLabel: "Tipu Sultan's Summer Palace",
    qualityScore: 88,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'city tour',
    rawAttributes: ['small_group'],
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-003',
    slug: 'malleswaram-food-walk',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-food',
    sourceProductId: 'bokun-food-22',
    title: 'Malleswaram Food & Filter Coffee Walk',
    shortDescription: 'Tiffin trails, century-old cafés, and market bites in a residential foodie quarter.',
    gamanaEditorialSummary:
      'Editorial favourite for travellers who want authentic South Indian breakfast culture—not mall food courts.',
    heroImageUrl: IMG(9585454),
    photoUrls: [IMG(9585454)],
    category: 'Food & Drink',
    experienceType: 'Guided Tour',
    tags: ['food', 'coffee'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 210,
    languages: ['English', 'Kannada'],
    difficultyLevel: 'easy',
    priceFrom: 2200,
    priceCurrency: 'INR',
    ratingValue: 4.9,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Malleswaram 18th Cross metro exit',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['6 tastings', 'Guide'],
    exclusions: ['Alcohol'],
    hasLinkedStory: false,
    qualityScore: 90,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'food tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-004',
    slug: 'cubbon-park-nature-walk',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-nature',
    sourceProductId: 'bokun-park-7',
    title: 'Cubbon Park Morning Nature Walk',
    shortDescription: 'Botanical highlights, colonial statuary, and birding in the cantonment green lung.',
    gamanaEditorialSummary: 'Best at dawn; combine with our Cubbon Park audio story the evening before.',
    heroImageUrl: IMG(1179229),
    photoUrls: [IMG(1179229)],
    category: 'Walking',
    experienceType: 'Guided Tour',
    tags: ['nature', 'parks'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Seshadripuram',
    latitude: 12.9763,
    longitude: 77.5929,
    durationMinutes: 120,
    languages: ['English'],
    difficultyLevel: 'easy',
    familyFriendly: true,
    priceFrom: 1200,
    priceCurrency: 'INR',
    ratingValue: 4.5,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Cubbon Park bandstand',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['Naturalist guide'],
    exclusions: [],
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000105',
    linkedStoryLabel: 'Cubbon Park',
    qualityScore: 85,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'walking tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-005',
    slug: 'iskcon-temple-spiritual-tour',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-spiritual',
    sourceProductId: 'bokun-temple-3',
    title: 'ISKCON Hill Temple Evening Experience',
    shortDescription: 'Architecture, aarti timing, and respectful visit guidance with a cultural host.',
    gamanaEditorialSummary:
      'Respect-first framing—ideal after our ISKCON story so visitors understand devotion etiquette.',
    heroImageUrl: IMG(5765818),
    photoUrls: [IMG(5765818)],
    category: 'Spiritual',
    experienceType: 'Guided Tour',
    tags: ['temple', 'evening'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Rajajinagar',
    durationMinutes: 90,
    languages: ['English', 'Hindi'],
    difficultyLevel: 'easy',
    minAge: 8,
    priceFrom: 999,
    priceCurrency: 'INR',
    ratingValue: 4.7,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Host', 'Prasad'],
    exclusions: ['Photography inside sanctum'],
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000106',
    linkedStoryLabel: 'ISKCON Temple',
    qualityScore: 86,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'temple tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-006',
    slug: 'nandi-hills-day-trip',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-daytrips',
    sourceProductId: 'bokun-nandi-1',
    title: 'Nandi Hills Sunrise Day Trip',
    shortDescription: 'Pre-dawn departure, fort viewpoints, and breakfast with transport from central Bengaluru.',
    gamanaEditorialSummary:
      'A full-morning escape; editorial note—bring layers; hilltop winds are cooler than the city.',
    heroImageUrl: IMG(1485894),
    photoUrls: [IMG(1485894)],
    category: 'Day Trips',
    experienceType: 'Day Trip',
    tags: ['sunrise', 'fort'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 360,
    languages: ['English', 'Hindi'],
    difficultyLevel: 'moderate',
    priceFrom: 3500,
    priceCurrency: 'INR',
    ratingValue: 4.4,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Transport', 'Breakfast', 'Guide'],
    exclusions: ['Personal expenses'],
    hasLinkedStory: false,
    qualityScore: 82,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'adventure',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-007',
    slug: 'lalbagh-botanical-guided',
    source: 'gamana_native',
    title: 'Lalbagh Botanical Stories Walk',
    shortDescription: 'Hyder Ali’s garden legacy with Gamana-curated plant and history stops.',
    gamanaEditorialSummary:
      'Native Gamana experience—unlock audio stories on-site, then optionally add a live horticulture guide.',
    heroImageUrl: IMG(1485894),
    photoUrls: [IMG(1485894)],
    category: 'Heritage',
    experienceType: 'Self-Guided Audio Tour',
    tags: ['garden', 'audio'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Lalbagh',
    latitude: 12.9507,
    longitude: 77.5848,
    durationMinutes: 90,
    languages: ['English', 'Kannada'],
    difficultyLevel: 'easy',
    familyFriendly: true,
    priceFrom: 499,
    priceCurrency: 'INR',
    ratingValue: 4.9,
    ratingSource: 'internal',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Lalbagh West Gate',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['Gamana audio access', 'Map'],
    exclusions: ['Live guide'],
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000100',
    linkedStoryLabel: 'Lalbagh Botanical Garden',
    qualityScore: 95,
    publicationStatus: 'published',
    bookableInApp: true,
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-008',
    slug: 'mysore-palace-day-excursion',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-daytrips',
    sourceProductId: 'bokun-mysore-2',
    title: 'Mysore Palace Day Excursion',
    shortDescription: 'Round-trip transport, palace entry, and guided interiors from Bengaluru.',
    gamanaEditorialSummary: 'Long day—best for heritage enthusiasts; not ideal with young children without breaks.',
    heroImageUrl: IMG(3581368),
    photoUrls: [IMG(3581368)],
    category: 'Day Trips',
    experienceType: 'Day Trip',
    tags: ['palace', 'mysore'],
    uiTabIntent: 'tours',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 600,
    languages: ['English'],
    difficultyLevel: 'easy',
    priceFrom: 4500,
    priceCurrency: 'INR',
    ratingValue: 4.3,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'on_request',
    instantConfirmation: false,
    inclusions: ['Transport', 'Guide', 'Palace ticket'],
    exclusions: ['Lunch'],
    hasLinkedStory: false,
    qualityScore: 78,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'city tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-009',
    slug: 'south-indian-cooking-class',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-workshops',
    sourceProductId: 'bokun-cook-5',
    title: 'South Indian Home Kitchen Masterclass',
    shortDescription: 'Hands-on dosa, sambar, and chutney with a home chef in Indiranagar.',
    gamanaEditorialSummary: 'Small-group favourite—book early weekends; apron and recipes included.',
    heroImageUrl: IMG(9585454),
    photoUrls: [IMG(9585454)],
    category: 'Workshops & Classes',
    experienceType: 'Class',
    tags: ['cooking', 'hands-on'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Indiranagar',
    durationMinutes: 180,
    languages: ['English'],
    difficultyLevel: 'easy',
    minAge: 12,
    priceFrom: 3200,
    priceCurrency: 'INR',
    ratingValue: 5.0,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Ingredients', 'Lunch', 'Recipes'],
    exclusions: ['Transport'],
    hasLinkedStory: false,
    qualityScore: 91,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'cooking class',
    rawAttributes: ['small_group'],
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-010',
    slug: 'bannerghatta-rafting-adventure',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-adventure',
    sourceProductId: 'bokun-raft-8',
    title: 'Outskirts River Rafting Session',
    shortDescription: 'Half-day whitewater intro with safety briefing and gear—moderate fitness required.',
    gamanaEditorialSummary: 'Adventure pick; not suitable for non-swimmers or guests under 14.',
    heroImageUrl: IMG(1365425),
    photoUrls: [IMG(1365425)],
    category: 'Water Activities',
    experienceType: 'Activity',
    tags: ['rafting', 'outdoor'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 300,
    languages: ['English', 'Hindi'],
    difficultyLevel: 'challenging',
    minAge: 14,
    priceFrom: 4200,
    priceCurrency: 'INR',
    ratingValue: 4.2,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Gear', 'Instructor', 'Snack'],
    exclusions: ['Photos package'],
    hasLinkedStory: false,
    qualityScore: 80,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'rafting',
    rawAttributes: ['outdoor'],
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-011',
    slug: 'visvesvaraya-museum-ticket',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-tickets',
    sourceProductId: 'bokun-museum-4',
    title: 'Visvesvaraya Industrial Museum Skip-the-Line',
    shortDescription: 'Timed entry ticket with optional science demo add-on for families.',
    gamanaEditorialSummary: 'Easy rainy-day activity; pair with Cubbon Park morning walk same day.',
    heroImageUrl: IMG(2846217),
    photoUrls: [IMG(2846217)],
    category: 'Attractions & Tickets',
    experienceType: 'Attraction Ticket',
    tags: ['museum', 'family'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    locality: 'Kasturba Road',
    durationMinutes: 120,
    languages: ['English', 'Kannada', 'Hindi'],
    difficultyLevel: 'easy',
    minAge: 4,
    familyFriendly: true,
    priceFrom: 350,
    priceCurrency: 'INR',
    ratingValue: 4.1,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Museum main gate',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['Timed entry'],
    exclusions: ['Guide'],
    hasLinkedStory: false,
    qualityScore: 75,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'museum ticket',
    rawAttributes: ['skip_the_line', 'family'],
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-012',
    slug: 'night-market-food-crawl',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-food',
    sourceProductId: 'bokun-night-9',
    title: 'VV Puram Night Food Crawl',
    shortDescription: 'Street-food lane tour with hygiene-conscious stops and local drink pairings.',
    gamanaEditorialSummary: 'Vibrant evening energy—editorial tip: eat light before you arrive.',
    heroImageUrl: IMG(9585454),
    photoUrls: [IMG(9585454)],
    category: 'Nightlife & Entertainment',
    experienceType: 'Activity',
    tags: ['street food', 'evening'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 150,
    languages: ['English', 'Kannada'],
    difficultyLevel: 'easy',
    priceFrom: 1800,
    priceCurrency: 'INR',
    ratingValue: 4.8,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Guide', '5 tastings'],
    exclusions: [],
    hasLinkedStory: false,
    qualityScore: 87,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'food tour',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-013',
    slug: 'silk-weaving-workshop',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-crafts',
    sourceProductId: 'bokun-silk-2',
    title: 'Silk Weaving Workshop & Loom Visit',
    shortDescription: 'Watch master weavers and try a handloom pattern in a cooperative studio.',
    gamanaEditorialSummary: 'Supports local artisans—meaningful souvenir context beyond mall silk.',
    heroImageUrl: IMG(3581364),
    photoUrls: [IMG(3581364)],
    category: 'Shopping & Local Crafts',
    experienceType: 'Workshop',
    tags: ['crafts', 'silk'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 120,
    languages: ['English'],
    difficultyLevel: 'easy',
    priceFrom: 2100,
    priceCurrency: 'INR',
    ratingValue: 4.6,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'meet_or_pickup',
    capacityType: 'on_request',
    instantConfirmation: false,
    inclusions: ['Demo', 'Small souvenir'],
    exclusions: [],
    hasLinkedStory: false,
    qualityScore: 84,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'workshop',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-014',
    slug: 'birding-lalbagh-nature',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-nature',
    sourceProductId: 'bokun-bird-3',
    title: 'Lalbagh Dawn Birding Session',
    shortDescription: 'Early-morning species spotting with a naturalist and binocular hire.',
    gamanaEditorialSummary: 'Nature & Wildlife pick—starts before 6 AM; worth it for photographers.',
    heroImageUrl: IMG(1485894),
    photoUrls: [IMG(1485894)],
    category: 'Nature & Wildlife',
    experienceType: 'Activity',
    tags: ['birding', 'nature'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 150,
    languages: ['English'],
    difficultyLevel: 'moderate',
    minAge: 10,
    priceFrom: 1600,
    priceCurrency: 'INR',
    ratingValue: 4.7,
    ratingSource: 'tripadvisor',
    pickupAvailable: false,
    meetingType: 'meet_on_location',
    meetingPointText: 'Lalbagh East Gate',
    capacityType: 'limited',
    instantConfirmation: true,
    inclusions: ['Naturalist', 'Binoculars'],
    exclusions: [],
    hasLinkedStory: true,
    linkedStoryId: '00000000-0000-0000-0000-000000000100',
    linkedStoryLabel: 'Lalbagh Botanical Garden',
    qualityScore: 83,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'adventure',
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-015',
    slug: 'brewery-craft-beer-tasting',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-night',
    sourceProductId: 'bokun-brew-1',
    title: 'Craft Brewery Tasting Flight',
    shortDescription: 'Three-microbrewery flight with food pairing in central Bengaluru.',
    gamanaEditorialSummary: '21+ only; editorial pick for expats and weekend visitors.',
    heroImageUrl: IMG(1267320),
    photoUrls: [IMG(1267320)],
    category: 'Nightlife & Entertainment',
    experienceType: 'Activity',
    tags: ['beer', 'tasting'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 120,
    languages: ['English'],
    difficultyLevel: 'easy',
    minAge: 21,
    priceFrom: 2800,
    priceCurrency: 'INR',
    ratingValue: 4.5,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['3 tastings', 'Snacks'],
    exclusions: ['Additional drinks'],
    hasLinkedStory: false,
    qualityScore: 79,
    publicationStatus: 'published',
    bookableInApp: true,
    createdAt: now,
    updatedAt: now,
  }),
  exp({
    id: 'exp-016',
    slug: 'airport-transfer-private',
    source: 'bokun',
    sourceVendorId: 'vendor-blr-transport',
    sourceProductId: 'bokun-airport-1',
    title: 'Private Airport Transfer (BLR)',
    shortDescription: 'Meet-and-greet driver from Kempegowda International to city hotels.',
    gamanaEditorialSummary: 'Reliable arrival option—fixed price, flight tracking included.',
    heroImageUrl: IMG(2104152),
    photoUrls: [IMG(2104152)],
    category: 'Transport & Transfers',
    experienceType: 'Transfer',
    tags: ['airport', 'transfer'],
    uiTabIntent: 'activities',
    city: 'Bengaluru',
    country: 'India',
    durationMinutes: 60,
    languages: ['English', 'Hindi'],
    difficultyLevel: 'not_specified',
    priceFrom: 1400,
    priceCurrency: 'INR',
    ratingValue: 4.4,
    ratingSource: 'tripadvisor',
    pickupAvailable: true,
    meetingType: 'pick_up',
    capacityType: 'free_sale',
    instantConfirmation: true,
    inclusions: ['Private car', 'Meet & greet'],
    exclusions: ['Tolls'],
    hasLinkedStory: false,
    qualityScore: 76,
    publicationStatus: 'published',
    bookableInApp: true,
    rawCategory: 'airport transfer',
    createdAt: now,
    updatedAt: now,
  }),
];
